# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - name: book-catalog
          image: book-catalog:latest  # Update this with your image name if you push it to a registry
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: "dpg-cr7h22i3esus7389oj50-a.singapore-postgres.render.com"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "sit722_part2_zdo7"
            - name: POSTGRES_USER
              value: "sit722_part2_zdo7_user"
            - name: POSTGRES_PASSWORD
              value: "xyOUKEjlrs0JAYdf9BqZDrAIg1ggmPZI"
